### ISSUE TITLE
The Town Kitchen - Wireframes and User Stories

### ISSUE THREAD

**Issue by MarinaMurashev** [the-town-kitchen/the-town-kitchen#1]
Wireframes and user stories are ready for review /cc @codepathreview @codepath @paulinar @XiangliDai 

wireframes are in the wireframes directory. The scans are a little bit hard to read, so here's a "higher fidelity" version of the wireframes: https://moqups.com/jemoonette/6pPEZtek/p:ad592cb44

We welcome your feedback.

**Comment by paulinar** [comment]
The scanned wireframes in the wireframes directory are a little bit hard to read, so here's a "higher fidelity" version:

https://moqups.com/jemoonette/6pPEZtek/p:ad592cb44

**Comment by paulinar** [comment]
The user stories have been modified on the README as of 11:24am today.

**Comment by nesquena** [comment]
Thanks for submitting this and documenting your progress so far! Good to see you have an initial version of the wireframes complete as a starting point for your app. 

Remember that by the end of your second sprint, we expect each team to have their core flows functionally complete (but rough) so this week your team should complete the first 50% of your core functionality. 

While building this app, try to keep in your mind the story for your app and what you need to have a polished demo.  Be aggressive about which features you can scope into the first version for internal demo day.  Excited to see what your group comes up with! Let us know what we can do to help.
