### ISSUE TITLE
Query - Order.java

### ISSUE THREAD

**Issue by HelloKashif** [the-town-kitchen/the-town-kitchen#32]
I'm trying to understand your code :) :+1: 
Can you clarify why the Order class contains attributes such as 'email' ( setting and getting emails also).
Shouldn't those be a part of the User?
eg. User 'has a' Order ==> User 'has a' email

**Comment by XiangliDai** [comment]
Right we do have a user column inside order table, I'm using email here since I think it will make query faster compare to query against object of user.
